[package]
name = "assignment"
version = "0.1.0"
authors = ["Pauravi Wagh <pwagh@iu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
url = "2.1"
anyhow = "1.0"